---
- name: Create an execution role for the containers
  amazon.aws.iam_role:
    name: "{{ prefix_v }}-container-execution-role"
    assume_role_policy_document: |
        {
          "Version":"2012-10-17",
          "Statement": [
            {
              "Sid": "",
              "Effect": "Allow",
              "Principal": {
                "Service": "ecs-tasks.amazonaws.com"
              },
              "Action": "sts:AssumeRole"
            }
          ]
        }
    managed_policies:
      - arn:aws:iam::aws:policy/service-role/AmazonECSTaskExecutionRolePolicy
    wait: true
  register: execution_role_r

- name: Create EFS targets list
  ansible.builtin.set_fact:
    efs_targets_f: >- 
      {{ (efs_targets_f | default([]) ) + [ { 'subnet_id': item, 'security_groups': [ security_group_v ] } ] }}
  loop: "{{ subnets_v }}"

- name: Allocate /data efs partition
  community.aws.efs:
    state: "present"
    name: "{{ prefix_v }}-data"
    targets: "{{ efs_targets_f }}"
  register: efs_data_r

- name: Allocate an ECS cluster for load execution
  community.aws.ecs_cluster:
    name: "{{ prefix_v }}-ecs-cluster"
    state: "present"
    capacity_providers:
      - FARGATE 
      - FARGATE_SPOT
    capacity_provider_strategy:
      - capacity_provider: FARGATE
        base: 1
        weight: 1
      - capacity_provider: FARGATE_SPOT
        weight: 100
    purge_capacity_providers: true

- name: Download map files to EFS volume
  ansible.builtin.include_tasks:
    file: download-files.yaml
