---

- name: Allocate osm download task_definition
  community.aws.ecs_taskdefinition:
    family: "{{ prefix_v }}-download-osm"
    state: "present"
    launch_type: FARGATE
    memory: 512
    cpu: 256
    network_mode: awsvpc
    execution_role_arn: "{{ execution_role_r.iam_role.arn }}"
    containers:
      - name: openmaptiles-tools
        image: "openmaptiles/openmaptiles-tools:latest"
        mountPoints:
          - sourceVolume: data
            containerPath: '/tileset'
            readOnly: false
        command:
          - download-osm
          - "{{ osm_region_v }}"
        logConfiguration:
          logDriver: awslogs
          options:
            awslogs-group: /ecs/n7m
            awslogs-region: "{{ region_v }}"
            awslogs-stream-prefix: ecs
    volumes:
      - name: data
        efsVolumeConfiguration:
          fileSystemId: "{{ efs_data_r.efs.file_system_id }}"

- name: Post-process the download file into a UID/GID mount point
  community.aws.ecs_taskdefinition:
    family: "{{ prefix_v }}-efs-configurator"
    state: "present"
    launch_type: FARGATE
    memory: 512
    cpu: 256
    network_mode: awsvpc
    execution_role_arn: "{{ execution_role_r.iam_role.arn }}"
    containers:
      - name: feed
        image: debian:bookworm-slim
        command:
          - /bin/bash
          - -x
          - -c
          - |
              rm -rf /data/{{ prefix_v }} || /bin/true
              mkdir /data/{{ prefix_v }} 
              mv /data/{{ osm_region_v }}-*.osm.pbf /data/{{ prefix_v }}/{{ osm_region_v }}-latest.osm.pbf
              chown -R 1001:1001 /data/{{ prefix_v }}
              rm /data/*.pbf || /bin/true
        mountPoints:
          - sourceVolume: data
            containerPath: '/data'
            readOnly: false
        logConfiguration:
          logDriver: awslogs
          options:
            awslogs-group: /ecs/n7m
            awslogs-region: "{{ region_v }}"
            awslogs-stream-prefix: ecs
    volumes:
      - name: data
        efsVolumeConfiguration:
          fileSystemId: "{{ efs_data_r.efs.file_system_id }}"

- name: Allocate grid and wiki download task_definition
  community.aws.ecs_taskdefinition:
    family: "{{ prefix_v }}-download-wiki-and-grid"
    state: "present"
    launch_type: FARGATE
    memory: 512
    cpu: 256
    network_mode: awsvpc
    execution_role_arn: "{{ execution_role_r.iam_role.arn }}"
    containers:
      - name: feed
        image: "ghcr.io/jonpspri/n7m-feed:latest"
        command:
          - download
          - --wiki
          - --grid
        mountPoints:
          - sourceVolume: data
            containerPath: '/data'
            readOnly: false
        logConfiguration:
          logDriver: awslogs
          options:
            awslogs-group: /ecs/n7m
            awslogs-region: "{{ region_v }}"
            awslogs-stream-prefix: ecs
    volumes:
      - name: data
        efsVolumeConfiguration:
          fileSystemId: "{{ efs_data_r.efs.file_system_id }}"
          rootDirectory: "/{{ prefix_v }}"

- name: Download the map data for selected region
  ecs_task:
    operation: run
    count: 1
    started_by: Ansible automation
    cluster: "{{ prefix_v }}-ecs-cluster"
    task_definition: "{{ prefix_v }}-download-osm"
    launch_type: FARGATE
    network_configuration:
      assign_public_ip: true
      subnets: "{{ subnets_v }}"
    wait_complete: true
  register: osm_task_r
  retries: 15  # It may take time for the IAM role to be aviable to ECS
  delay: 20

- name: Check OSM download result
  ansible.builtin.fail:
    msg: "OSM download task failed: {{ osm_task_r.task[0].stoppedReason | default('Unknown reason') }}"
  when: >
    osm_task_r.task[0].stopCode is defined and
    osm_task_r.task[0].stopCode != 'EssentialContainerExited' or
    osm_task_r.task[0].containers[0].exitCode | default(1) != 0

- name: Configurate the EFS mount
  ecs_task:
    operation: run
    count: 1
    started_by: Ansible automation
    cluster: "{{ prefix_v }}-ecs-cluster"
    task_definition: "{{ prefix_v }}-efs-configurator"
    launch_type: FARGATE
    network_configuration:
      assign_public_ip: true
      subnets: "{{ subnets_v }}"
    wait_complete: true
  register: configurator_task_r

- name: Check OSM download result
  ansible.builtin.fail:
    msg: "Configurator task failed: {{ configurator_task_r.task[0].stoppedReason | default('Unknown reason') }}"
  when: >
    configurator_task_r.task[0].stopCode is defined and
    configurator_task_r.task[0].stopCode != 'EssentialContainerExited' or
    configurator_task_r.task[0].containers[0].exitCode | default(1) != 0

- name: Download the grid and wiki data
  ecs_task:
    operation: run
    count: 1
    started_by: Ansible automation
    cluster: "{{ prefix_v }}-ecs-cluster"
    task_definition: "{{ prefix_v }}-download-wiki-and-grid"
    launch_type: FARGATE
    network_configuration:
      assign_public_ip: true
      subnets: "{{ subnets_v }}"
    wait_complete: true
  register: grid_wiki_task_r

- name: Check grid and wiki data download result
  ansible.builtin.fail:
    msg: "Grid/wiki download task failed: {{ grid_wiki_task_r.task[0].stoppedReason | default('Unknown reason') }}"
  when: >
    grid_wiki_task_r.task[0].stopCode is defined and
    grid_wiki_task_r.task[0].stopCode != 'EssentialContainerExited' or
    grid_wiki_task_r.task[0].containers[0].exitCode | default(1) != 0

